<?php
define("HTTP_EMAIL_INVALIDE", 601);
define("HTTP_DENOMINATION_INVALIDE", 602);
define("HTTP_TEL_INVALIDE", 603);
define("HTTP_MDP_CONFIRM_DIFF", 604);
define("HTTP_CODE_POSTAL_INVALIDE", 605);
define("HTTP_VILLE_INVALIDE", 606);
define("HTTP_ADRESSE_INVALIDE", 607);
define("HTTP_SIRET_INVALIDE", 608);
define("HTTP_CLE_AUTH_INVALIDE", 609);

define("HTTP_OK", 200);
?>